package com.narasimhahs.blesampleclient;

import java.util.UUID;

class Constants {
    static String SERVICE_STRING = "7D2EA28A-F7BD-485A-BD9D-92AD6ECFE93E";
    static UUID SERVICE_UUID = UUID.fromString(SERVICE_STRING);

    static String LED_SERVICE_STRING = "E093F3B5-00A3-A9E5-9ECA-40016E0EDC24";
    static UUID LED_SERVICE_UUID = UUID.fromString(SERVICE_STRING);

    static String CHARACTERISTIC_ECHO_STRING = "7D2EBAAD-F7BD-485A-BD9D-92AD6ECFE93E";
    static UUID CHARACTERISTIC_ECHO_UUID = UUID.fromString(CHARACTERISTIC_ECHO_STRING);

    static String CHARACTERISTIC_TIME_STRING = "7D2EDEAD-F7BD-485A-BD9D-92AD6ECFE93E";
    static UUID CHARACTERISTIC_TIME_UUID = UUID.fromString(CHARACTERISTIC_TIME_STRING);

    static String CHARACTERISTIC_LED_BALLAST_STRING = "E093F3B7-00A3-A9E5-9ECA-40036E0EDC24";
    static UUID CHARACTERISTIC_LED_BALLAST_UUID = UUID.fromString(CHARACTERISTIC_LED_BALLAST_STRING);

    private static String CLIENT_CONFIGURATION_DESCRIPTOR_STRING = "00002902-0000-1000-8000-00805f9b34fb";
    static UUID CLIENT_CONFIGURATION_DESCRIPTOR_UUID = UUID.fromString(CLIENT_CONFIGURATION_DESCRIPTOR_STRING);

    static final String CLIENT_CONFIGURATION_DESCRIPTOR_SHORT_ID = "2902";

    static final long SCAN_PERIOD = 10000;
}
